// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="decade_counter_decade_counter,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu11p-flga2577-1-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=1.498143,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=5,HLS_SYN_LUT=57,HLS_VERSION=2023_2}" *)

module decade_counter (
        ap_clk,
        ap_rst,
        reset,
        slowena,
        out_r
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input  [0:0] reset;
input  [0:0] slowena;
output  [3:0] out_r;

reg   [3:0] count;
reg   [3:0] ap_phi_mux_count_loc_1_phi_fu_58_p6;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] reset_read_read_fu_36_p2;
wire   [3:0] select_ln18_fu_85_p3;
wire   [0:0] slowena_read_read_fu_42_p2;
wire   [0:0] icmp_ln18_fu_73_p2;
wire   [3:0] add_ln21_fu_79_p2;
reg   [0:0] ap_NS_fsm;
wire    ap_ST_fsm_state1_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 count = 4'd0;
#0 ap_CS_fsm = 1'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((reset_read_read_fu_36_p2 == 1'd1)) begin
            count <= 4'd0;
        end else if (((slowena_read_read_fu_42_p2 == 1'd1) & (reset_read_read_fu_36_p2 == 1'd0))) begin
            count <= select_ln18_fu_85_p3;
        end
    end
end

assign ap_ST_fsm_state1_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if (((slowena_read_read_fu_42_p2 == 1'd0) & (reset_read_read_fu_36_p2 == 1'd0))) begin
            ap_phi_mux_count_loc_1_phi_fu_58_p6 = count;
        end else if (((slowena_read_read_fu_42_p2 == 1'd1) & (reset_read_read_fu_36_p2 == 1'd0))) begin
            ap_phi_mux_count_loc_1_phi_fu_58_p6 = select_ln18_fu_85_p3;
        end else if ((reset_read_read_fu_36_p2 == 1'd1)) begin
            ap_phi_mux_count_loc_1_phi_fu_58_p6 = 4'd0;
        end else begin
            ap_phi_mux_count_loc_1_phi_fu_58_p6 = 'bx;
        end
    end else begin
        ap_phi_mux_count_loc_1_phi_fu_58_p6 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln21_fu_79_p2 = (count + 4'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign icmp_ln18_fu_73_p2 = ((count == 4'd9) ? 1'b1 : 1'b0);

assign out_r = ap_phi_mux_count_loc_1_phi_fu_58_p6;

assign reset_read_read_fu_36_p2 = reset;

assign select_ln18_fu_85_p3 = ((icmp_ln18_fu_73_p2[0:0] == 1'b1) ? 4'd0 : add_ln21_fu_79_p2);

assign slowena_read_read_fu_42_p2 = slowena;

endmodule //decade_counter
