-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity perform_logic_operation is
port (
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    A : IN STD_LOGIC_VECTOR (0 downto 0);
    B : IN STD_LOGIC_VECTOR (0 downto 0);
    op : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of perform_logic_operation is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "perform_logic_operation_perform_logic_operation,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu11p-flga2577-1-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=1.311000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=44,HLS_VERSION=2023_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal and_ln6_fu_58_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_fu_54_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln4_2_fu_94_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln8_fu_70_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln10_fu_76_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln4_1_fu_88_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln4_fu_82_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln12_fu_64_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln4_fu_108_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln4_fu_100_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln4_1_fu_114_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ce_reg : STD_LOGIC;


begin



    and_ln6_fu_58_p2 <= (B and A);
    ap_done <= ap_start;
    ap_idle <= ap_const_logic_1;
    ap_ready <= ap_start;
    ap_return <= 
        select_ln4_fu_100_p3 when (or_ln4_fu_108_p2(0) = '1') else 
        select_ln4_1_fu_114_p3;
    empty_fu_54_p1 <= op(2 - 1 downto 0);
    icmp_ln4_1_fu_88_p2 <= "1" when (empty_fu_54_p1 = ap_const_lv2_2) else "0";
    icmp_ln4_2_fu_94_p2 <= "1" when (empty_fu_54_p1 = ap_const_lv2_1) else "0";
    icmp_ln4_fu_82_p2 <= "1" when (empty_fu_54_p1 = ap_const_lv2_3) else "0";
    or_ln4_fu_108_p2 <= (icmp_ln4_2_fu_94_p2 or icmp_ln4_1_fu_88_p2);
    or_ln8_fu_70_p2 <= (B or A);
    select_ln4_1_fu_114_p3 <= 
        xor_ln12_fu_64_p2 when (icmp_ln4_fu_82_p2(0) = '1') else 
        and_ln6_fu_58_p2;
    select_ln4_fu_100_p3 <= 
        or_ln8_fu_70_p2 when (icmp_ln4_2_fu_94_p2(0) = '1') else 
        xor_ln10_fu_76_p2;
    xor_ln10_fu_76_p2 <= (B xor A);
    xor_ln12_fu_64_p2 <= (ap_const_lv1_1 xor and_ln6_fu_58_p2);
end behav;
